extends RefCounted

# Evidence, not a definitive explanation. The figure remains unnamed.
const RECORDS := {
	"I": "NORTH SURVEY / 17 OCTOBER 1896\n\nThe captain counted twelve bedrolls. I drew eleven. At sunrise neither of us could remember the missing name.\n\nSomeone has moved the bridge. My ink insists it has always been here.\n\nA rule, underlined twice: never put the place you call home on the same sheet as this coast.",
	"II": "SECOND SURVEY / 17 OCTOBER 1896\n\nThe date is unchanged. The fire has burned for three nights.\n\nWe thought the blank spaces meant nobody had been here. They were deliberate omissions. Someone before us knew what not to draw.\n\nA map joins two points even when no road exists. Perhaps that is what opened the way. Follow the real river, not the remembered ridge.",
	"IV": "DO NOT CONTINUE\n\nThe handwriting is mine. The ink is older than the sign.\n\nThe third survey has been cut from the ledger. Only its binding remains: a strip of skin bearing a compass rose.\n\nI have crossed out my name. Under it someone has written it again.\n\nDON'T FOLLOW IT. The last word has been amended: DON'T LET IT FOLLOW YOU.",
	"home": "THE HOUSE WITHOUT A FAMILY\n\nMy jungle chart is on the table. A wet dot marks this room. Beyond its border is the street where I grew up. I never drew that street here.\n\nA child's exercise book repeats a sentence: a name is an address.\n\nThe final page lists our expedition. Eleven names. A twelfth line is waiting for ink.",
	"archive": "THE ATLAS OF ABSENCES\n\nThe city has no census, only maps. Where a person should be recorded, a road has been drawn.\n\nA censor's instruction: leave the centre blank. Copy no eyes. Do not sign the finished sheet.\n\nEvery chart contains a small black figure. On some it stands at an exit. On others the exit has been erased.\n\nA cave plan is filed under FUTURE EXPEDITIONS. It predates written language.",
	"inn": "THE INNKEEPER\n\nHow is the expedition going? You draw very well.\n\nI ask how he knows. He turns his cup over. There is no bottom to it.\n\nWe don't know, he says. We remember.\n\nHis ledger contains tomorrow's breakfast order, in my handwriting. Beneath it: one guest will not require a room.\n\nHe stops smiling. He noticed you.",
	"tower": "THE WINDOW THAT LOOKS IN\n\nAnother cartographer copies my hand. When I stop, he continues.\n\nA note scratched into the glass: the blind one does not need eyes. It sees through what is shown to it.\n\nBefore ink, they used ochre. Before paper, they used stone. The warning was never about looking. It was about bringing the shape back with you."
}

const CAVE := [
	"A procession surrounds a river and a fire. One person has no head; another has two shadows.\n\nThe curve of the river is exact. This is our camp, painted before there were names for its trees.\n\nAbove it, a handprint has been scraped away. Someone understood that a signature was a path home.",
	"Red eyes beneath a closed eye. The animal is tethered to a figure by a line that runs through every room.\n\nThe little people are not worshipping it. They are removing their own footprints.\n\nA later hand has scratched a warning over the first: THE HUNTER FOLLOWS THE LINE, NOT THE FLESH.",
	"A labyrinth surrounds a key. Two knots interrupt the route to a white doorway.\n\nEach knot is a closed eye crossed by a human hand. They are seals: two places where the observer has been written into the map.\n\nBreak both witnesses. Take the key. Leave no name behind.\n\nThe first maps were warnings, not invitations.",
	"A palm beside a vast eye. Someone has painted a familiar house inside its pupil.\n\nThe house is crossed out. Then painted again. Then crossed out.\n\nIt does not chase them out of the cave. It waits for them to show it where to look.\n\nDO NOT SHOW IT WHERE YOU LIVE."
]

const RUINS := [
	["THE SURVEYOR'S OATH", "I mark the river, not the thing beneath it.\nI mark the shore, not the name it calls me.\nI leave the centre blank.\n\nThe final line has been worn away by countless hands."],
	["EXPEDITION V", "Our expedition symbol. The stone is older than our country.\n\nBelow it: RETURNED / eleven. DEPARTED / twelve.\n\nSomeone has chiselled out the word returned."],
	["A BROKEN COMPASS", "The needle points toward the wall. Behind it, something breathes.\n\nOn the casing: instruments locate what they have been taught to seek.\n\nA folded scrap inside shows two seals and a key. The exit is not enough while your name is still written here."],
	["EXPEDITION VII", "The names have been replaced with paths. One ends at a bedroll. One ends at a desk. One goes off the edge of the stone.\n\nThe smallest mark resembles a person. It has no corresponding name."],
	["THE UNSIGNED CHART", "The map is complete except for the centre and the signature.\n\nSomeone escaped far enough to write: breaking a witness closes a road. It does not make the god forget the traveller.\n\nThe rest has been carefully removed."]
]

const OBSERVATORY := "THE UNLISTED OBSERVATORY\n\nThree bearings converge on the same blank point. There should be a mountain there. My instruments show a depth.\n\nThe slate names R'lyeh: a drowned city whose sleeper reaches people through dreams. Someone has copied the same skyline without ever seeing the sea.\n\nThe drawing is not a memory. It is an answer to a call.\n\nSURVEY CONCLUSION: my chart has connected our camp to something already dreaming. Follow the eastern ridge to the terminus."
const CHAPEL := "THE THRESHOLD CABINET\n\nSomeone brought old protective marks into this city: circles, rosettes and looping scratches beside the door. The annotation calls them attempts to trap a harmful passage.\n\nDo not confuse them with the red eyes. The eyes are witnesses: my name written where the dream can find it.\n\nAn exhibition poster names Nyarlathotep. The host's face is scratched out. Is it a name, a disguise or another false explanation?\n\nThe little figure has no caption."
const EXHIBITION := "THE EXHIBITION OF IMPOSSIBLE ANGLES\n\nThe demonstrator projects the campfire onto a wall. The image has more tents than we erected. Someone sleeping beside the fire raises his head.\n\nA room whose angles add up wrongly is not merely a badly drawn room. Here, geometry chooses which place touches which.\n\nA note invokes a crawling chaos, Nyarlathotep. It is a theory, not a proven identity.\n\nCONCLUSION: the city is using my memories to draw a route back to me. The old cave shows how to cut it."
const SUMMARIES := {
	"jungle":"The expedition records predate us. The empty places were deliberate. Our maps may connect places that should remain apart.",
	"sea":"The chart is answering another dream. R'lyeh names the submerged presence in the archive's account; I cannot confirm what is beneath my ship.",
	"city":"The city knows the expedition because it has my memories. My signature gives the dream an address. I need the older warnings below it.",
	"cave":"The cave teaches an escape: erase both red witnessing eyes, take the brass key, reach the light. Wisps are not promises of safety.",
	"maze":"Two witnesses bind my name to the ruin. Breaking them closes those roads. The key opens the physical exit. Escape may not erase what has noticed me."
}
const FIELD_GUIDE := "MYTHOS & FOLKLORE / ADAPTATION NOTES\n\nCTHULHU & R'LYEH: Lovecraft's The Call of Cthulhu connects a submerged city, dream impressions and assembled evidence. The ocean is inspired by those motifs, not a complete literal adaptation.\n\nNYARLATHOTEP: the original story presents a disturbing demonstrator, nightmares and a city becoming unfamiliar. Our exhibition echoes that role; neither host nor small figure has a confirmed identity.\n\nDREAM GEOMETRY: The Dreams in the Witch House joins angles, mathematics and dream travel. Our supernatural mapping rules are original fiction.\n\nANCIENT MURALS: The Nameless City uses a descent and murals to reveal nonhuman history. Our ochre warnings teach real game objectives.\n\nPROTECTIVE MARKS: historical marks have been interpreted as protection at thresholds. Interpretation varies. They are not the red witnessing seals.\n\nGHOST LIGHTS: folklore includes lights that warn, mislead or guide. The wisps do not guarantee safety.\n\nThe blind presence is not claimed to be Azathoth. Map-signatures, two witnesses and the unnamed figure belong to this game's own lore.\n\nSources and adaptation distinctions are recorded in RESEARCH.md in the project folder."
